"""empty message

Revision ID: 9b43a83da8be
Revises: 
Create Date: 2026-06-02 16:58:59.107520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b43a83da8be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('next_scrape', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('products', 'source',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint(op.f('products_asin_key'), 'products', type_='unique')
    op.drop_column('products', 'asin')
    op.alter_column('users', 'notification_channel',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('email', 'sms', name='notificationchannel'),
               existing_nullable=True,
postgresql_using='notification_channel::notificationchannel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notification_channel',
               existing_type=sa.Enum('email', 'sms', name='notificationchannel'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.add_column('products', sa.Column('asin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('products_asin_key'), 'products', ['asin'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'source',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('products', 'next_scrape')
    # ### end Alembic commands ###
