"""empty message

Revision ID: d31cb82a1fee
Revises: 
Create Date: 2026-06-05 09:14:24.501712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31cb82a1fee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('price_history_product_id_fkey'), 'price_history', type_='foreignkey')
    op.create_foreign_key('price_history_product_id_fkey', 'price_history', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_products_user_id_fkey'), 'user_products', type_='foreignkey')
    op.drop_constraint(op.f('user_products_product_id_fkey'), 'user_products', type_='foreignkey')
    op.create_foreign_key('user_products_user_id_fkey', 'user_products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_products_product_id_fkey', 'user_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_products_user_id_fkey', 'user_products', type_='foreignkey')
    op.drop_constraint('user_products_product_id_fkey', 'user_products', type_='foreignkey')
    op.create_foreign_key(op.f('user_products_product_id_fkey'), 'user_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('user_products_user_id_fkey'), 'user_products', 'users', ['user_id'], ['id'])
    op.drop_constraint('price_history_product_id_fkey', 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('price_history_product_id_fkey'), 'price_history', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
